### ISSUE TITLE
Pattern matching on attributes with string interpolation throws a compilation error when calling `refute_email_sent/1`

### ISSUE THREAD

**Issue by GabCamarda** [swoosh/swoosh#797]
### Describe the bug

When asserting an email with specific attributes was not sent, having some of the attributes as string literal with interpolation expressions throws a compilation error. This is only encountered when using `refute_email_sent` and having non-literal (e.g. variables or functions) in the interpolation expression. The counterpart `assert_email_sent` does not throw any errors when called with the same attributes. 

Looking at some of the past PRs, it looks like this started happening with the omission of `Macro.escape/1` in [this PR](https://github.com/swoosh/swoosh/pull/702/files#diff-01bde7845e9adb2331d3c4461e7721a0daef508943a256c48a934a1578b40295R179.). 

This issue was encountered when upgrading Swoosh from 1.6.4 -> 1.11.4.

### Steps to Reproduce the Bug or Issue

Writing a simple unit test such as this below
```elixir
    test "testing swoosh issue" do
      refute_email_sent subject: "some issue with interpolation for #{to_string(3)}"
    end
```
is sufficient for the compilation error to be raised:
```elixir
 error: cannot invoke remote function String.Chars.to_string/1 inside a match
   test/mailer/services/send_email_test.exs:2: Mailer.Service.SendEmailTest."test call/1 testing swoosh
 issue"/1
```

The same happens with variables for example:
```elixir
    test "testing swoosh issue" do
      user = %{name: "name", slug: "123abc"}
      refute_email_sent subject: "some issue with interpolation for #{user.name}"
    end
```
Same error:
```elixir
 error: cannot invoke remote function user.name/0 inside a match
   test/mailer/services/send_email_test.exs:2: Mailer.Service.SendEmailTest."test call/1 testing swoosh
 issue"/1
```

However, if the string literal with interpolation is assigned to a variable, such as the following:
```elixir
    test "testing swoosh issue" do
      subject = "some issue with interpolation for #{to_string(3)}"
      refute_email_sent subject: ^subject
    end
```
No errors are raised:
```elixir
 *..
 Finished in 0.6 seconds (0.6s async, 0.00s sync)
 1 tests, 0 failures
```

### Expected behavior

I believe it should be allowed to use string literal with interpolation.

### Platform

- OTP: 25
- Elixir: 1.15.3

**Comment by princemaple** [comment]
Would you like to try this experimental test module instead? https://hexdocs.pm/swoosh/Swoosh.X.TestAssertions.html

With enough people testing it, it will eventually replace the current one.

**Comment by GabCamarda** [comment]
Sure, don't mind! One of the nice additions I was looking forward in the new release was the ability to assert multiple emails being sent. Do you think that would be added, eventually, to the new assertion module?

Btw, taking a closer look at how the `refute_received` macro is implemented in the source code, it ultimately boils down to the issue being an Elixir limitation with pattern matching. 
E.g.

`{:subject, "some string #{some_var}"} = pattern`

Which is not allowed in Elixir.

**Comment by princemaple** [comment]
> Do you think that would be added, eventually, to the new assertion module?

Yup for sure. It just depends on contributors' and my spare time.

> it ultimately boils down to the issue being an Elixir limitation with pattern matching.

Yep, that was the limitation. And the new module eliminates most of the macro magic.

**Comment by GabCamarda** [comment]
Nice, thank you.

If I were to introduce the new assertion modules in the codebase of the company I work for, how safe/ready are the modules for production use?

**Comment by princemaple** [comment]
It is open source. Everyone can check the source code themselves.

It passes our own tests. Yes test utilities have tests as well...

No guarantees. We aren't paid to provide an SLA or anything.

**Comment by GabCamarda** [comment]
Of course and thank you for your great work!

Since you mentioned it was experimental, I was mostly referring to how experimental it is, which stage of the release it is (e.g alpha, beta, etc.). But no worries, I'll give it a try and report back my findings.

Thank you!

**Comment by princemaple** [comment]
It's not feature complete, i.e. on par with the current one.

It's pretty solid though. Less magic less headache.
